### ISSUE TITLE
Check for non-space whitespace in titles

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/outernet-metadata#7]
Titles should not contain any whitespace other than space character (and space equivalents in other langauges). Currently this does not seem to be the case.

**Comment by ben-en** [comment]
Where should this be handled? On import?

**Comment by foxbunny** [comment]
In the validator.

**Comment by ben-en** [comment]
Oh, obviously, as that's where the issue is. Heh.

**Comment by ben-en** [comment]
Fixed in 87d4e19b72a2149460d57992a126acf7b0184b31
